### ISSUE TITLE
zwcfg and zwscene files not saved

### ISSUE THREAD

**Issue by zsandrus** [hassio-addons/addon-zwave2mqtt#3]
# Problem/Motivation
When the zwave2mqtt container is restarted the zwcfg_hex.xml and zwscene.xml files are not saved since the folder they are saved in is not where the data volume is mounted (/opt). This is preventing node names and locations from being persisted.

## Expected behavior
When the container is restarted the zwcfg_hex.xml and zwscene.xml files should be persisted.

## Actual behavior
The zwcfg_hex.xml and zwscene.xml files are removed since they are not stored in a volume.

## Steps to reproduce
Install addon, enable 'Save configuration' setting, restart addon.

## Proposed changes
The files should be saved and loaded from /opt/store instead of /opt since that is where the data volume is mounted.

**Comment by RualdOrdelman** [comment]
It looks I got the some problem. 

Thanks for this great add-on. 

I tried to migrate from HA with Zwave with an Aeon Labs USB stick to this component. After configuring the basics I got the first nodes available in Zwave2Mqtt, but all the Zwave node information etc is empty because the add-on starts with a empty OpenZwave config. 

I found the option to import an Zwave config file, so I uploaded my Zwcfg config file from the HA root directory but it looks that won't work. I don't see any difference. 

After a few minutes a few of the 50 nodes I got have some Zwave node information. I give the Add-on a restart and after that all the node information was gone again. 

So a few problems / suggestions for the manual:
1) Why the Zwcfg file import doesn't work. I don't see any error or something. Maybe because of the 1.4 <---> 1.6 difference? 
2) Where in the add-on container is the local Zwcfg file located? I tried to find it but I can only find the /opt directory with the web application files but without the Zwcfg file.
3) Make the Zwcfg persistent so after a restart not all the node information is gone
4) An option to link an config file or something from outside the container inside would be great. So the config file could be on an central place instead of inside an add-on container.

**Comment by RualdOrdelman** [comment]
@frenck the main problem looks like the Zwcfg file in /opt is not persistent. 

I've tried to change the Zwave Config Path to /data, because /data is mapped as a volume. Unfortunately the add-on does not pick up the change and still saves it in / opt in the zwcfg config.

**Comment by joshkay** [comment]
Looks like I'm running into the same issue.  I have a backup of my zwave config, but uploading it doesn't seem to do anything.  All my motion sensors are showing up with empty products and are not reporting properly anymore.  Also the names and locations are wiped, which breaks the way I had setup my mqtt configuration.

After a config change it also seems to stop the addon and requires a restart to get the frontend up and running again.

**Comment by rudders** [comment]
Same issue here - I never got the original addon to work but once I upgraded it was much better at recognising my devices but not if I try and change the config I get the following and the addon continually restarts - uninstalling and reinstalling is all I can do to get one good run - but any further configuration causes this error on restart of zwave2mqtt.

`fs.js:114
    throw err;
    ^
Error: ENOENT: no such file or directory, unlink 'zwcfg_0xecb5285a.xml'
    at Object.unlinkSync (fs.js:956:3)
    at files.forEach.file (/opt/lib/ZwaveClient.js:192:16)
    at Array.forEach (<anonymous>)
    at fs.readdir (/opt/lib/ZwaveClient.js:189:15)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)`

**Comment by rgruyters** [comment]
This issue has been fixed by PR https://github.com/hassio-addons/addon-zwave2mqtt/pull/4. This issue can now be closed.

**Comment by frenck** [comment]
It has not.

**Comment by rgruyters** [comment]
I haven't tested the upload function to be true, but config files are saved in the correct folder, `/opt/store` which is a symlink to `/data` and are now persistent.
The initial issue was about the config files are not saved in correct folder. This has been fixed in PR #4 
If there other issues with the config files, shouldn't we open a new issue for it?

**Comment by foughtgeoduck** [comment]
still not working still looking in /opt/ only

**Comment by frenck** [comment]
@foughtgeoduck It is still not working, because this issue is still open. There is an issue with the build process, I'm awaiting an upstream release.

**Comment by frenck** [comment]
v0.3.0 has been shipped and addresses this issue.
