### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by sanderlv** [hassio-addons/addon-zwave2mqtt#56]
Since today, on several PCs and several browsers:
![image](https://user-images.githubusercontent.com/16528916/81566118-b63e3c00-939a-11ea-9b68-73383c9aec5f.png)

icons are al gone... what's wrong?

**Comment by 4lloyd** [comment]
I had the same issue in the past, but that was caused by a bug in Zwave2MQTT. The problem was that the icons where loaded via the internet instead of via Zwave2MQTT itself.

The problem was solved a few days ago: [https://github.com/OpenZWave/Zwave2Mqtt/issues/508](url). And the latest version of this addon should contain the version with the fix.

**Comment by sanderlv** [comment]
Thanks, but too bad. I stopped using openzwave2mqtt and have now started tocuse the QT openzwave plugin.
